In [4]:
np.e

2.718281828459045

In [5]:
np.pi

3.141592653589793

In [7]:
np.log(2)

0.69314718055994529

In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
np.array([1.0,2.0,3.0])

array([ 1.,  2.,  3.])

In [10]:
a=np.array([1,2,3])
a=_8

In [11]:
print (a.dtype)

int32


In [17]:
b= np.array([1,2,3],dtype= float)

In [18]:
print (b)

[ 1.  2.  3.]
